version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout

      - setup_remote_docker

      - aws-cli/setup

      # - run:
      #     name: Start Docker build environment
      #     command: make build_env

      # - run:
      #     name: Run UI Tests
      #     command: make test_ui

      # - run:
      #     name: Run Backend Tests
      #     command: make test_backend

      # - run:
      #     name: Run Integration Tests
      #     command: make test_integration

      # - run:
      #     name: Build the App image
      #     command: make build

      - run:
          name: "Deploy to ECS"
          command: |
            if [ "${CIRCLE_BRANCH}" == "ci" ]; then
                make deploy
            fi

      # - run:
      #     name: Tear down build environment
      #     command: make clean            

orbs:
  aws-cli: circleci/aws-cli@1.0.0      