version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker
      - run: make build_env
      - run: docker exec something-backend-build sh -c "ls -l"
      - run: make test_all
      - run: make cleanup
